version: '3'
services:
  db-bodacc:
    build:
      context: ./dbbodacc
    volumes:
      - ./dbbodacc/init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=bodacc
      - POSTGRES_USER=bodacc
      - POSTGRES_PASSWORD=bodacc
  postgrest:
    build: 
      context: ./api
      args: 
        - POSTGREST_VERSION=v7.0.1
    environment:
      - POSTGRES_DB_HOST=db-bodacc
      - POSTGRES_DB=bodacc
      - POSTGRES_USER=bodacc
      - POSTGRES_PASSWORD=bodacc
    depends_on:
      - db-bodacc
    ports:
      - "3345:3000"
